import { useEffect, useMemo, useState, type ReactNode } from 'react'
import { AccessTimeRounded, ArrowForwardRounded, CheckCircleRounded, ErrorOutlineRounded, SecurityRounded, ShieldRounded, VpnKeyRounded } from '@mui/icons-material'
import { Alert, Avatar, Box, Button, Card, CardContent, Divider, LinearProgress, MenuItem, Select, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, ToggleButton, ToggleButtonGroup, Typography } from '@mui/material'
import { alpha } from '@mui/material/styles'
import { useNavigate } from 'react-router-dom'
import { fetchAuditLogPage, fetchDashboardSummary, fetchDashboardTrend, fetchKeys } from '../api/kms'
import { StatusBadge } from '../components/common/StatusBadge'
import { useAuth } from '../hooks/useAuth'
import type { AuditLog, CryptoKey, DashboardSummary, DashboardTrend, KeyStatus } from '../types/api'
import { isAdminRole } from '../types/auth'
import { getStatusLabel } from '../utils/status'

const statusColors: Record<KeyStatus, string> = { CREATED: '#8a6cc5', ACTIVE: '#2e9b69', REACTIVATED: '#d92f81', DEACTIVATED: '#ef8b2c', EXPIRED: '#d95c45', INACTIVE: '#87909f', DISTRIBUTED: '#368aca', COMPROMISED: '#c93451', DESTROYED: '#4f5663' }
interface SummaryCardProps { label: string; value: string; note: string; color: string; icon: ReactNode; href: string }

function SummaryCard({ label, value, note, color, icon, href }: SummaryCardProps) {
  const navigate = useNavigate()
  return <Card role="link" tabIndex={0} onClick={() => navigate(href)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') navigate(href) }} sx={{ cursor: 'pointer', height: '100%' }}><CardContent sx={{ p: '20px !important' }}><Box sx={{ display: 'flex', justifyContent: 'space-between' }}><Box><Typography sx={{ color: 'text.secondary', fontSize: 13.5, fontWeight: 700 }}>{label}</Typography><Typography sx={{ mt: 0.6, fontSize: 31, fontWeight: 850 }}>{value}</Typography></Box><Avatar sx={{ bgcolor: alpha(color, 0.12), color }}>{icon}</Avatar></Box><Typography sx={{ mt: 1.5, color: 'text.secondary', fontSize: 13 }}>{note}</Typography></CardContent></Card>
}

function formatDate(date: Date) { return date.toISOString().slice(0, 10) }
function formatKst(value: string) { return new Intl.DateTimeFormat('ko-KR', { timeZone: 'Asia/Seoul', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date(value)) }

function UsageChart({ trend }: { trend: DashboardTrend | null }) {
  const points = trend?.points ?? []
  const [active, setActive] = useState(Math.max(points.length - 1, 0))
  useEffect(() => setActive(Math.max(points.length - 1, 0)), [points.length])
  if (!points.length) return <Box sx={{ display: 'grid', height: 250, placeItems: 'center', color: 'text.secondary' }}>조회 기간의 키 사용 기록이 없습니다.</Box>
  const width = Math.max(720, points.length * 42)
  const max = Math.max(1, ...points.flatMap((point) => [point.encryptions, point.decryptions, point.keysCreated]))
  const coords = (field: 'encryptions' | 'decryptions' | 'keysCreated') => points.map((point, index) => ({ x: 32 + index * ((width - 64) / Math.max(1, points.length - 1)), y: 198 - (point[field] / max) * 145 }))
  const path = (field: 'encryptions' | 'decryptions' | 'keysCreated') => coords(field).map((point, index) => `${index ? 'L' : 'M'} ${point.x} ${point.y}`).join(' ')
  const selected = points[Math.min(active, points.length - 1)]
  return <Box><Stack direction="row" spacing={2} sx={{ my: 1 }}>{[['암호화', '#d92f81'], ['복호화', '#7652b8'], ['키 생성', '#32a6c9']].map(([label, color]) => <Stack key={label} direction="row" spacing={0.6} sx={{ alignItems: 'center' }}><Box sx={{ width: 8, height: 8, borderRadius: 1, bgcolor: color }} /><Typography sx={{ fontSize: 12.5, color: 'text.secondary' }}>{label}</Typography></Stack>)}</Stack><Box sx={{ px: 1.5, py: 1, mb: 1, borderRadius: 2, bgcolor: 'action.hover' }}><Typography sx={{ fontSize: 13.5, fontWeight: 800 }}>{selected.period} · 암호화 {selected.encryptions} · 복호화 {selected.decryptions} · 키 생성 {selected.keysCreated}</Typography></Box><Box sx={{ overflowX: 'auto' }}><Box component="svg" viewBox={`0 0 ${width} 240`} sx={{ display: 'block', minWidth: width, width: '100%', height: 240 }}>{[0, .25, .5, .75, 1].map((ratio) => <g key={ratio}><line x1="32" x2={width - 32} y1={198 - ratio * 145} y2={198 - ratio * 145} stroke="#e4e7ed" /><text x="34" y={193 - ratio * 145} fill="#8b93a1" fontSize="10">{Math.round(max * ratio)}</text></g>)}<path d={path('encryptions')} fill="none" stroke="#d92f81" strokeWidth="3" /><path d={path('decryptions')} fill="none" stroke="#7652b8" strokeWidth="3" /><path d={path('keysCreated')} fill="none" stroke="#32a6c9" strokeWidth="2" strokeDasharray="5 4" />{points.map((point, index) => { const x = coords('encryptions')[index].x; return <g key={point.period}><line x1={x} x2={x} y1="53" y2="198" stroke={index === active ? '#6c4bb0' : 'transparent'} strokeDasharray="3 4" /><rect role="button" tabIndex={0} aria-label={`${point.period} 데이터 선택`} x={x - 20} y="48" width="40" height="175" fill="transparent" onMouseEnter={() => setActive(index)} onClick={() => setActive(index)} /><text x={x} y="220" textAnchor="middle" fill={index === active ? '#6c4bb0' : '#8b93a1'} fontSize="10">{point.period.slice(5)}</text></g>})}</Box></Box></Box>
}

function Dashboard() {
  const { user } = useAuth(); const navigate = useNavigate()
  const [summary, setSummary] = useState<DashboardSummary | null>(null); const [keys, setKeys] = useState<CryptoKey[]>([]); const [trend, setTrend] = useState<DashboardTrend | null>(null); const [activities, setActivities] = useState<AuditLog[]>([])
  const [period, setPeriod] = useState<'DAY' | 'MONTH'>('DAY'); const [expiryDays, setExpiryDays] = useState(30); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { const to = new Date(); const from = new Date(to); if (period === 'DAY') from.setDate(from.getDate() - 29); else from.setMonth(from.getMonth() - 11); void fetchDashboardTrend(formatDate(from), formatDate(to), period).then(setTrend).catch(() => setError('키 사용 추이를 불러오지 못했습니다.')) }, [period])
  useEffect(() => { setLoading(true); const requests: Promise<unknown>[] = [fetchDashboardSummary().then(setSummary), fetchKeys().then(setKeys)]; if (isAdminRole(user?.role)) requests.push(fetchAuditLogPage({ from: '', to: '', actor: '', action: 'ALL', page: 0, size: 5 }).then((page) => setActivities(page.content))); void Promise.all(requests).catch(() => setError('대시보드 실데이터를 불러오지 못했습니다.')).finally(() => setLoading(false)) }, [user?.role])
  const statusDistribution = useMemo(() => Object.entries(keys.reduce<Partial<Record<KeyStatus, number>>>((counts, key) => ({ ...counts, [key.status]: (counts[key.status] ?? 0) + 1 }), {})).map(([status, value]) => ({ status: status as KeyStatus, value: value ?? 0 })), [keys])
  const expiringKeys = useMemo(() => keys.map((key) => ({ ...key, days: Math.ceil((new Date(`${key.expireAt}T23:59:59`).getTime() - Date.now()) / 86_400_000) })).filter((key) => key.status !== 'DESTROYED' && key.days >= 0 && key.days <= expiryDays).sort((a, b) => a.days - b.days), [keys, expiryDays])
  const summaryItems: SummaryCardProps[] = [
    { label: '전체 관리 키', value: String(summary?.totalKeys ?? 0), note: 'DB crypto_key 전체', color: '#d92f81', icon: <VpnKeyRounded />, href: '/keys' },
    { label: '암호화 가능', value: String(summary?.encryptCapableKeys ?? 0), note: '현재 정책상 암호화 허용', color: '#2e9b69', icon: <CheckCircleRounded />, href: '/keys' },
    { label: '복호화 가능', value: String(summary?.decryptCapableKeys ?? 0), note: '현재 정책상 복호화 허용', color: '#7652b8', icon: <ShieldRounded />, href: '/keys' },
    { label: '⚠️ 만료 임박 키', value: String(expiringKeys.length), note: `${expiryDays}일 이내 확인 필요`, color: '#d74343', icon: <AccessTimeRounded />, href: '/keys' },
    { label: '무결성 위반', value: String(summary?.integrityViolations ?? 0), note: summary?.integrityViolations ? '즉시 격리·조사 필요' : '검증 결과 정상', color: '#c93451', icon: <SecurityRounded />, href: '/keys' },
  ]
  const total = Math.max(keys.length, 1); let offset = 0
  const donut = `conic-gradient(${statusDistribution.map(({ status, value }) => { const start = offset; offset += value / total * 100; return `${statusColors[status]} ${start}% ${offset}%` }).join(', ') || '#e5e7eb 0 100%'})`
  return <Box><Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2.5 }}><Typography variant="h5">대시보드</Typography><StatusBadge status={user?.role ?? 'CLIENT'} label={`${user?.role ?? ''} VIEW`} /></Box>{error && <Alert severity="error" onClose={() => setError('')} sx={{ mb: 2 }}>{error}</Alert>}{loading && <LinearProgress sx={{ mb: 2 }} />}<Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: 'repeat(2,1fr)', xl: 'repeat(5,1fr)' }, gap: 2 }}>{summaryItems.map((item) => <SummaryCard key={item.label} {...item} />)}</Box>
    <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', lg: 'minmax(0,2fr) minmax(300px,.8fr)' }, gap: 2, mt: 2 }}><Card><CardContent><Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><Typography variant="h6">키 생성·사용 추이</Typography><ToggleButtonGroup exclusive size="small" value={period} onChange={(_e, value) => value && setPeriod(value)}><ToggleButton value="DAY">일</ToggleButton><ToggleButton value="MONTH">월</ToggleButton></ToggleButtonGroup></Box><UsageChart trend={trend} /></CardContent></Card><Card><CardContent><Typography variant="h6">키 상태</Typography><Box sx={{ display: 'grid', placeItems: 'center', py: 2 }}><Box sx={{ position: 'relative', display: 'grid', width: 150, height: 150, placeItems: 'center', borderRadius: '50%', background: donut, '&::after': { content: '""', position: 'absolute', width: 100, height: 100, borderRadius: '50%', bgcolor: 'background.paper' } }}><Box sx={{ zIndex: 1, textAlign: 'center' }}><Typography sx={{ fontSize: 28, fontWeight: 850 }}>{keys.length}</Typography><Typography sx={{ fontSize: 12, color: 'text.secondary' }}>DB 전체</Typography></Box></Box></Box><Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(2,1fr)', gap: 1 }}>{statusDistribution.map(({ status, value }) => <Box key={status} sx={{ display: 'flex', justifyContent: 'space-between' }}><Stack direction="row" spacing={.7} sx={{ alignItems: 'center' }}><Box sx={{ width: 8, height: 8, borderRadius: 1, bgcolor: statusColors[status] }} /><Typography sx={{ fontSize: 12.5 }}>{getStatusLabel(status)}</Typography></Stack><Typography sx={{ fontSize: 12.5, fontWeight: 800 }}>{value}</Typography></Box>)}</Box></CardContent></Card></Box>
    <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', xl: 'minmax(320px,.8fr) minmax(0,1.7fr)' }, gap: 2, mt: 2 }}>{isAdminRole(user?.role) && <Card><CardContent><Box sx={{ display: 'flex', justifyContent: 'space-between' }}><Typography variant="h6">최근 활동</Typography><Button size="small" endIcon={<ArrowForwardRounded />} onClick={() => navigate('/my/recent-activity')}>전체보기</Button></Box><Box sx={{ mt: 1.5 }}>{activities.length === 0 && <Typography sx={{ color: 'text.secondary', py: 3 }}>기록된 활동이 없습니다.</Typography>}{activities.map((activity, index) => <Box key={activity.logUid}><Box sx={{ py: 1.2 }}><Stack direction="row" sx={{ justifyContent: 'space-between' }}><Typography sx={{ fontSize: 13.5, fontWeight: 750 }}>{activity.action}</Typography><Typography sx={{ fontSize: 12, color: 'text.secondary' }}>{formatKst(activity.createdAt)}</Typography></Stack><Typography noWrap sx={{ mt: .3, fontSize: 12.5, color: 'text.secondary' }}>{activity.actor} · {activity.detail}</Typography></Box>{index < activities.length - 1 && <Divider />}</Box>)}</Box></CardContent></Card>}
      <Card sx={{ border: expiringKeys.some((key) => key.days <= 7) ? '2px solid' : undefined, borderColor: expiringKeys.some((key) => key.days <= 7) ? 'error.main' : undefined }}><CardContent><Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><Typography variant="h6" color={expiringKeys.length ? 'error.main' : 'text.primary'}>🚨 만료 임박 키</Typography><Stack direction="row" spacing={1} sx={{ alignItems: 'center' }}><Select size="small" value={expiryDays} onChange={(event) => setExpiryDays(Number(event.target.value))}><MenuItem value={7}>7일</MenuItem><MenuItem value={30}>30일</MenuItem><MenuItem value={60}>60일</MenuItem></Select><StatusBadge label={`${expiringKeys.length}건`} tone="danger" /></Stack></Box><TableContainer sx={{ mt: 1.5 }}><Table size="small"><TableHead><TableRow><TableCell>키 이름</TableCell><TableCell>알고리즘</TableCell><TableCell>상태</TableCell><TableCell>만료일</TableCell><TableCell>위험도</TableCell></TableRow></TableHead><TableBody>{expiringKeys.length === 0 && <TableRow><TableCell colSpan={5} align="center" sx={{ py: 4 }}>기준 내 만료 예정 키가 없습니다.</TableCell></TableRow>}{expiringKeys.map((key) => <TableRow key={key.keyUid} hover sx={{ bgcolor: key.days <= 7 ? alpha('#d32f2f', .08) : alpha('#ed6c02', .05) }}><TableCell><Typography sx={{ fontWeight: 800 }}>{key.days <= 7 ? '🔥 ' : '⚠️ '}{key.keyName}</Typography><Typography sx={{ fontSize: 10.5, color: 'text.secondary', fontFamily: 'monospace' }}>{key.keyUid}</Typography></TableCell><TableCell>{key.algorithm}-{key.keySize}/{key.mode}</TableCell><TableCell><StatusBadge status={key.status} /></TableCell><TableCell>{key.expireAt}</TableCell><TableCell><Stack direction="row" spacing={1} sx={{ alignItems: 'center' }}><LinearProgress variant="determinate" value={Math.max(10, 100 - key.days / expiryDays * 100)} color={key.days <= 7 ? 'error' : 'warning'} sx={{ width: 55 }} /><Typography color={key.days <= 7 ? 'error.main' : 'warning.dark'} sx={{ fontWeight: 900 }}>D-{key.days}</Typography></Stack></TableCell></TableRow>)}</TableBody></Table></TableContainer>{expiringKeys.length > 0 && <Stack direction="row" spacing={.7} sx={{ mt: 1.5, color: 'error.main' }}><ErrorOutlineRounded fontSize="small" /><Typography sx={{ fontSize: 13, fontWeight: 750 }}>갱신 정책과 서비스 영향을 즉시 확인하세요.</Typography></Stack>}</CardContent></Card></Box>
  </Box>
}
export default Dashboard
